### ISSUE TITLE
Registration: SSL Handshake error: The issuer certificate could not be found

### ISSUE THREAD

**Issue by skobkin** [mumble-voip/backend-services#3]
My  server disappeared from the list again (mumble-voip/mumble#5774). I'm getting following error in the logs:

```
   <W>2023-07-20 00:47:01.528 1 => Registration: SSL Handshake error: The issuer certificate could not be found
   <W>2023-07-20 00:47:01.539 1 => Registration failed: SSL handshake failed
```

I've thought that it's because my image could be too old and you might have used some new CA for your certificate.
But I've just built a new image based on alpine:3.18 with 1.5.517 RC altogether and the error is still there.

**Comment by Krzmbrzl** [comment]
@davidebeatrici

**Comment by davidebeatrici** [comment]
The error that you see is sent by the registration script: there is an issue with the certificate that is set on your Mumble server.

**Comment by skobkin** [comment]
@davidebeatrici What is the issue?
It works just fine, Mumble shows root channel with green background.

![image](https://github.com/mumble-voip/backend-services/assets/967576/f18deeec-0d7f-47e4-9b9b-ff6a30ed7f31)

You can check it yourself: `mumble.skobk.in`

[Gatus](https://status.skobk.in/endpoints/02-services_mumble-server-tls) which uses TLS connection to check if everything is fine also has no problems with the certificate.

![image](https://github.com/mumble-voip/backend-services/assets/967576/015e0aeb-8cfa-4729-9ba4-f3be387486e8)

Could it be that registration script has outdated CA certs?

**Comment by skobkin** [comment]
@davidebeatrici Can you suggest something that I can check to help with solving this issue?

I asked a bunch of server users and everyone was saying that they also see green background on server root channel and didn't see any warnings from mumble about bad certificate.

I have acme.sh set up, so it'll automatically restart Mumble container after issuing new certificate.

**Comment by skobkin** [comment]
@Krzmbrzl @davidebeatrici, Guys?

**Comment by skobkin** [comment]
Several certificates were changed since the issue was created. Server is still not being shown in the catalog.

![image](https://github.com/mumble-voip/backend-services/assets/967576/3c28352a-51e2-4421-b776-1bfc62974e2f)

@davidebeatrici

**Comment by skobkin** [comment]
After updating to 1.5.0 RC2 ([changes](https://gitlab.com/skobkin/docker-murmur/-/commit/9ebf8cafbcf035b987d5b880f8714bb0f1407b39)) server is back again.

If you fixed something in the back-end or in the Murmur then thank you. If not then you can close this issue, I guess 🤷

**Comment by davidebeatrici** [comment]
We only updated the server's OS, there might have been an issue with OpenSSL.

Glad to hear the issue is fixed though!
